### ISSUE TITLE
Move (some) Consistency Enforcement code into Rucio github repository

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#303]

**Comment by klannon** [comment]
@ivmfnal This issue was moved to done without being closed and with no linked PR or comments to give any idea what actual work was done.  Could you please add at least a comment to explain what was done and then close the issue?  (Or change the status to reflect the actual situation if this issue cannot be closed yet?)

**Comment by ivmfnal** [comment]
I do not think we need to duplicate every task both a
