### ISSUE TITLE
Implement daemon-less Rucio Consistency Enforcement procedures

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#304]

**Comment by ivmfnal** [comment]
The new code has been in testing/debugging since Monday 8/22/2022.
Currently in dry run mode - the lists of dark and missing replicas to act on are produced but not sent to Rucio.
Old code is running in parallel for comparison.
However, the comparison is not very meaningless because old daemons fail for most sites for various reasons - need to be debugged/fixed

**Comment by ivmfnal** [comment]
There are 2 versions of the monitor, showing old and new stats for CE actions:

Old: https://cmsweb.cern.ch/rucioconmon/index
New: https://cmsweb.cern.ch/rucioconmon/new/index
