### ISSUE TITLE
Make rules more robust for WMTransferor rule deletion by ops

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#309]
Including operational improvements

WMCore microservices perhaps

**Comment by cmoore24-24** [comment]
Planned work with Alan to implement REST API to make rule updating in WM simpler

**Comment by ericvaandering** [comment]
Connor will describe new ops procedures briefly in the issue and then close.

**Comment by cmoore24-24** [comment]
Procedures added to CMS Operator Handbook: https://docs.google.com/document/d/1kZsB5z9mCbZLUTBKdLbSki3njUkGEafJwBjXPDyDlNE/edit#heading=h.646wylc4j7w4

All WM rules must be treated more carefully than others. Methods for unstucking that do not require deleting/remaking the rule should be used and exhausted first. If need be, contacting the WM team before deleting the rule is required, and they must be informed of the new rule promptly after the issue is resolved.
