### ISSUE TITLE
fix Rucio MQ connection problem in Hermes and Kronos #356

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#368]

**Comment by yuyiguo** [comment]
created the first PR to debug hermes
upgrade stopm.py to the current version
made a new SC8 VM, loaded with podman and other required tools/libraries.
Built test images that are running on rucio int.
Examined hermes daemon log files.
learning/studing hermes code.

**Comment by yuyiguo** [comment]
We studied Rucio MQ connection using Hermes. We found there was no connection problem on the test broker (cms-test-mb.cern.ch) with continuously 500 messages/send which is way higher than the average Kronos or Herms message rate. 

This ticket was opened because we get the below alerts from the AMQ broker from time to time. Recently we got these several a day.

```
The number of stored messages for cms-rucio-tracer-kronos@cms (/queue/Consumer.kronos.cms.rucio.tracer)
is unexpected: 1.29009e+06.

CERN Messaging Service: http://cern.ch/messaging
Monitoring Dashboards:  http://cern.ch/messaging/grafana

Exception: client:messages_stored
Status: FAILURE
Entities: cms-rucio-tracer-kronos@cms
Producer: mig

```

We simulated the high sending rate to the broker and studied the monitoring for Kronos for the past two weeks' data. We think the unexpectedly high number of stored messages was caused by the number of consumers dropping dramatically. 

In Fig 1, from 12/30 to 01/06, the two big jumps in the "message stored" is in the same time slots where the "consumers" had two big dips. 

In Fig 2, When the "message stored" reached above 500K from normally close to 0, the consumers drop to around 5 from normally close to 20. 

So we need to find out why our message reader drops from time to time. We opened a ticket to followup on this. The new ticket is [#400](https://github.com/dmwm/CMSRucio/issues/400).


Fig 1.
![Image](https://user-images.githubusercontent.com/1775438/211098816-fbcf0d32-fd52-4884-a1dc-557ad4288682.png)

Fig 2. 

![Image](https://user-images.githubusercontent.com/1775438/211098837-c857a2a9-345e-4cb6-a369-266ff14ef446.png)
