### ISSUE TITLE
Help users to move over from their old space to rucio space

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#405]
As per discussion at the meeting for DM of user data. 
We need to start discussing the best way to let the user import their data in `/store/user/<username>` into the RUCIO land.

This is a tricky point, it involves a change of ownership and it is not clear to me what is the most efficient way we can afford.

I'd let @dynamic-entropy summarize what are the alternatives, since similar discussion were brought up during some of use case he worked on.

But then I'd like to have opinions from @ericvaandering @KatyEllis and @belforte at least. We are likely overlooking some details.

**Comment by belforte** [comment]
IIUC 2. means to register in Rucio files owned by user. The problem is that Rucio account may not be able to delete them if needed and there is not even a guaranteed that reading is possible. So for long term sanity a copy will always be  needed. Maybe 2. can be a way to do the copy indicated in 1. w/o typing gfal commands, i.e. asking Rucio to do it.

**Comment by dynamic-entropy** [comment]
Hi @belforte

At the moment, rucio does not delete files in Temp_RSEs, since there are usually no transfers by rucio to them (IIRC rucio only has read permissions in Temp) and no space freeing is required by rucio. So this copy still remains intact (Neither rucio nor temp cleanup removes it).

The `/store/temp` is periodically cleaned by external services/or manually by some scripts (I think 15 days is the retention period). This creates another issue, that such replicas, even though deleted, appear in rucio as available at these Temp_RSEs. Confirmed by @dciangot 

I did not understand the second part, as to how do we ask rucio to do a transfer without registering the files as dids in its catalogue. 
The copy created in `1` is to enable that registration, this copy will be removed by the temp cleanup in some time.
The actual and final copy will be created by the rucio rule in the common steps.

**Comment by belforte** [comment]
IMHO permission for Rucio to delete files in Temp_RSE is needed and will have to be setup by sites. As you indicate removing files by other means while Rucio things there is a replica there, is no good.

Sorry about my second part, most likely what I wrote makes no sense because I had misunderstood your 2. Maybe you can expand a bit ? Do you mean to allow dids of the form `/store/user/belforte/...` releasing the constrain to be limited to `/store/user/rucio/belforte` ? And what shall we do with those files than ? Or do you mean keep dids as `/store/user/belforte/...` but allow the PFN to be `/store/user/belforte/...` exploiting the non-deterministi did/PFN association in Temp_RSE ?

**Comment by dynamic-entropy** [comment]
The latter. The DIDs still remain, `/store/user/rucio/belforte/...`  but we allow rucio to register/read files from the with the `/store/user/` prefix for Temp_RSEs. 

At the moment, we only allow registering files in `/store/temp` namespace for Temp_RSEs. 
For e.g. 
```
c.add_replica(
    rse = 'T2_CH_CERN_Temp', 
    scope = 'user.rchauhan',
    name = '/store/user/rucio/belforte/myfile',
    pfn="davs://eoscms.cern.ch:443/eos/cms/store/user/belforte/myfile"
)
```
will result in 
```
rucio.common.exception.RSEFileNameNotSupported: RSE does not support provided filename.
Details: Invalid prefix: provided '/eos/cms/store/user', expected '/eos/cms/store/temp/'
```

**Comment by belforte** [comment]
thanks Rahul. Understood. I like this approach. Let me summarise to make sure I understood: we register in Rucio the current file(s) in `/store/user/joe` on Temp_RSE, ask Rucio to replicate in `/store/user/rucio/joe` on RSE and then remove the replicas in `/store/user/joe` from Rucio DB and up to the user to clean up their "old" disk. Much better than asking permission for Rucio to delete data from `/store/user/joe`. Files never physically go on the Temp_RSE disk, but we need that Lfn2Pfn done via the TempRSE rules, retrieves a PFN (including protocol and host) which can access `/store/user`. Trivial if `/store/user` and `/store/temp` are on same storage server, but I am not sure that this is the case everywhere. If it works on all sites but a few, we can surely go for it and find ways to deal with the exceptional ones as ... exceptions !

**Comment by dynamic-entropy** [comment]
> Trivial if `/store/user` and `/store/temp/user` are on same storage server, but I am not sure that this is the case everywhere.

How can I test/verify this for all sites?

**Comment by dciangot** [comment]
> Files never physically go on the Temp_RSE disk, but we need that Lfn2Pfn done via the TempRSE rules, retrieves a PFN (including protocol and host) which can access `/store/user`. Trivial if `/store/user` and `/store/temp/user` are on same storage server,

Why is that needed? The only thing that matters in this scenario is that the rucio proxy can read data from /store/user and indeed it can everywhere. There is no Lfn2pfn for non-deterministic RSEs, you specify the pfn by hand. What am I missing?

**Comment by belforte** [comment]
I was not sure if we store only the path of the full PFN including protocol/host part.  Sorry. Yes, things are simpler than I wrote.
As far as testing, I guess it is as simple as to list `/store/user` at all sites using the Lfn2Pfn mapping from that RSE. 

On this topic it would be nice to have either a rucio command or an ad hoc script to be used as bash command where you supply LFN and RSE and get the PFN. Currently that info is only available via python. I do not know if now one should also indicate if I want an xroot or webdav endpoint (i.e. the correct values for lfns2pfns operation and scheme args)

**Comment by dynamic-entropy** [comment]
So, this will require that we allow the prefix, `/store/user/` in the protocol setting of the Te,p_RSEs.
Which I think, will mean, allowing everything under `/store/` since there is a simple, "starts with" check in Rucio. Is this a good idea? @ericvaandering @belforte @dciangot 

https://github.com/rucio/rucio/blob/2b23466beec4372ae6ae25b1e3e2a69501788a27/lib/rucio/rse/protocols/protocol.py#L418-L419

I see that for Temp_RSEs, the prefix is the only difference in the protocol configurations when setting up the RSE. 
https://github.com/dmwm/CMSRucio/blob/d32abd9935f1be5397fcd9407b856a9322adf4d6/docker/CMSRucioClient/scripts/CMSRSE.py#L341-L352

**Comment by ericvaandering** [comment]
It's a little more complicated than that. The prefix isn't ALLOWED, it's appended to every file. So if we made such a change to allow the Temp RSE to "see" /store/user files, then /store/temp wouldn't work.

Maybe we should consider a new RSE type _Migrate (which we would delete when this is done). This would be the same prefixes as the real RSEs but non-deterministic. So we could register files there with /store/rucio/USER LFNs and /store/user PFNs and transfer stuff out. Then delete the RSE.

**Comment by dciangot** [comment]
I think this comes down to doing a central migration or not. I must admit that I'd rather avoid to migrate everything from `/store/user/username` (I'd expect that maybe 20% of the total space is really used), instead I'd prefer to let the user migrate and try the rucio capabilities first and then import only what they really need. In this scenario the _Migrate RSE might stay there until we decide to deprecate `/store/user/username` namespace - not sure if this is something we can afford either.

So now we are left with scenario 1. or _Migrate RSEs

Ideas? opionion?

**Comment by dciangot** [comment]
all in all, I have an executive proposal. I'd try to tackle the following use case first:
- I'm a user with a dataset published on phys03 DBS and I want to import this into RUCIO namespace/control

For these, we should have everything on CRAB to provide users with some example tasks to achive that. So for now, I'm in favor of moving this issue out of CMSRucio issues and close it.

https://github.com/dmwm/CRABServer/issues/7537
