### ISSUE TITLE
Remove obsolete ddm_quotas

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#527]
https://github.com/dmwm/CMSRucio/blob/e89e7c661fb106eb8ec3e5ede19c44c5bb599243/DMOps/dynamic_ddmquota_update.py#LL47C1-L60C22

We have a bunch of old ddm_quotas that were overridden due to various reasons but forgotten thereafter. 
Remove those that are not required anymore, e.g. Estonia

-----

Additionally, I would suggest using an RSE attribute, let's call it `override_ddm_quota` to set it for future operational uses.

**Comment by dynamic-entropy** [comment]
Hello! 
I do not know when and who set it up (most probably Benedikt, since it runs as a cron job or maybe Nick, I have heard about it from him too). 


So, the production uses `ddm_quota` as weight in the rules they create. 
This value is set as the amount of free space on the site. 
From my tests on the rucio weighted algorithm, it serves the intention, but the frequency of the updates is too slow (seems like once per day), and it will break at busy sites very easily, like yesterday at CERN and I had to override it.
This particular commit does not change how it works, only refactors it to be able to override the values using RSE attributes.

**Comment by ericvaandering** [comment]
OK, I was going to suggest that it go into the 12 hour cron job, but it sounds like 1 hour really is needed, huh?

I think, then it should be added to that shell script and we stop running it "somewhere else". I want everything that impacts the system running under the Rucio system. Having it tweaked from outside is not good because it will get forgotten about

**Comment by dynamic-entropy** [comment]
Moved it to hourly cron, in #547. Please have a look
