### ISSUE TITLE
Bug: Helm chart changes not propagated

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#750]
### Bug Description

Although the helm chart https://github.com/dmwm/CMSRucio/blob/master/helm/rucio-cron-jobs had correct values, the IAM client_id was not updated on the kubernetes cronjob.

### Reproduction Steps

1. change the client id in the helm values
2. observe the resulting cronjob after flux sync (if any)

### Related Issues

Related to #684

**Comment by dciangot** [comment]
To be investigated, not expected.

**Comment by ericvaandering** [comment]
I think I'm just going to close this.  The correct way to do this is to update the chart, update the chart version, and then update flux if necessary to pull the new chart version. Also, the chart values should be settable in rucio-flux which will override what's here. 

PERHAPS if there is no value set in flux and all you do is change the value you did, things will reconcile. But it may take longer since we don't pull the charts often (once an hour if memory serves).
