### ISSUE TITLE
Enhancement: Upgrade the prometheus helm charts?

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#782]
### Enhancement Description

Currently, we run the Prometheus-community's Prometheus chart version `15.18.0` which installs a Prometheus version `v2.39.1`. (Released on [Oct 7, 2022](https://github.com/prometheus/prometheus/releases?q=2.39.1&expanded=true))

@ericvaandering Shall we upgrade the chart version to latest `(25.x.x)` or perhaps one version below `(24.x.x)` which install prometheus version `v2.51.x.`

### Use Case

At this point, there is no immediate functional requirement.
However, it makes future upgrades easier as well as brings improvements introduced since the version used.

**Comment by ericvaandering** [comment]
I thought I tried a later version and had issues. But I didn’t investigate. We can certainly try but may have to find the latest version working for us and do some debugging.


Sent from a mobile device.

On Apr 19, 2024, at 4:09 AM, Rahul Chauhan ***@***.***> wrote:

﻿

[EXTERNAL] – This message is from an external sender

Enhancement Description

Currently, we run the Prometheus-community's Prometheus chart version 15.18.0 which installs a Prometheus version v2.39.1. (Released on Oct 7, 2022<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_prometheus_prometheus_releases-3Fq-3D2.39.1-26expanded-3Dtrue&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=_InDEGXaJi8qmfzIIkg5hft3J91nk0iPiHOY__F6JMsTS5vsI_wMSqP6TF_Wwnpw&s=iBYo0E6VV8iDaqboks35pGL9ZCmJ4uGVaVLhOynYmzM&e=>)

@ericvaandering<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ericvaandering&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=_InDEGXaJi8qmfzIIkg5hft3J91nk0iPiHOY__F6JMsTS5vsI_wMSqP6TF_Wwnpw&s=97oM3Pze5L3hXkuY6SwS0CWrqq-rM0CmXojmfr7-49k&e=> Shall we upgrade the chart version to latest (25.x.x) or perhaps one version below (24.x.x) which install prometheus version v2.51.x.

Use Case

At this point, there is no immediate functional requirement.
However, it makes future upgrades easier as well as brings improvements introduced since the version used.

Possible Solution

No response

Related Issues

No response

**Comment by dynamic-entropy** [comment]
I upgraded this on integration and everything seems to work fine.
